export {default as gitHub} from "./gitHub.svg"
export {default as instagram} from "./instagram.svg"
export {default as linkedIn} from "./linkedIn.svg"
export {default as moon} from "./moon.svg"
export {default as sun} from "./sun.svg"
export {default as twitter} from "./twitter.svg"
export {default as vk} from "./vk.svg"
