export {default as img01} from "./01.jpg"
export {default as img02} from "./02.jpg"
export {default as img03} from "./03.jpg"
export {default as img04} from "./04.jpg"
export {default as img05} from "./05.jpg"
export {default as img06} from "./06.jpg"

export {default as imgBig01} from "./01-big.jpg"
export {default as imgBig02} from "./02-big.jpg"
export {default as imgBig03} from "./03-big.jpg"
export {default as imgBig04} from "./04-big.jpg"
export {default as imgBig05} from "./05-big.jpg"
export {default as imgBig06} from "./06-big.jpg"